### ISSUE TITLE
Rename namespace to Anno.FileDBModels

### ISSUE THREAD

**Issue by jakobharder** [Shad0wlife/AnnoFileDBModels#1]
Namespaces should not include underscores.

You can have `Anno.FileDBModels` as your default namespace and also name your project accordingly without any problems.

**Comment by Shad0wlife** [comment]
> name your project accordingly without any problems

So you mean Anno.FileDBModels.sln and Anno.FileDBModels.csproj?

**Comment by jakobharder** [comment]
Yep, that's what I meant :)

**Comment by Shad0wlife** [comment]
Closed with 0032b1574c4c81009295365b7e434e9046810d95.
